import React from "react";
function Features() {
  return (
    <div className="relative bg-white py-16 sm:py-24 lg:py-32">
      <div className="mx-auto max-w-md px-4 text-center sm:max-w-3xl sm:px-6 lg:max-w-7xl lg:px-8">
        <h2 className="text-base font-semibold uppercase tracking-wider text-indigo-600">
          Key Features
        </h2>
        <p className="mt-2 text-3xl font-extrabold tracking-tight text-gray-900 sm:text-4xl">
          Built with cutting edge AI technology.
        </p>
        <p className="mx-auto mt-5 max-w-prose text-xl text-gray-500">
          {" "}
          LumenAI, leverages advanced machine learning algorithms to provide
          accurate and early predictions based on medical imaging and data. With
          an intuitive user interface, it empowers healthcare professionals and
          patients to analyze results efficiently, ensuring faster
          decision-making. The app also prioritizes accessibility and security,
          making it a reliable companion in the fight against breast cancer.
        </p>
      </div>
      <div className="mt-12">
        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
          <div className="pt-6">
            <div className="flow-root rounded-lg bg-gray-50 px-6 pb-8">
              <div className="-mt-6">
                <div>
                  <span className="inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 shadow-lg">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      className="h-6 w-6 text-white"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M9 12.75 11.25 15 15 9.75M21 12c0 1.268-.63 2.39-1.593 3.068a3.745 3.745 0 0 1-1.043 3.296 3.745 3.745 0 0 1-3.296 1.043A3.745 3.745 0 0 1 12 21c-1.268 0-2.39-.63-3.068-1.593a3.746 3.746 0 0 1-3.296-1.043 3.745 3.745 0 0 1-1.043-3.296A3.745 3.745 0 0 1 3 12c0-1.268.63-2.39 1.593-3.068a3.745 3.745 0 0 1 1.043-3.296 3.746 3.746 0 0 1 3.296-1.043A3.746 3.746 0 0 1 12 3c1.268 0 2.39.63 3.068 1.593a3.746 3.746 0 0 1 3.296 1.043 3.746 3.746 0 0 1 1.043 3.296A3.745 3.745 0 0 1 21 12Z"
                      />
                    </svg>
                  </span>
                </div>
                <h3 className="mt-8 text-lg font-medium tracking-tight text-gray-900">
                  Accurate predictions generated by powerful Deep Learning
                  Models.{" "}
                </h3>
                <p className="mt-5 text-base text-gray-500">
                  Our app harnesses the power of advanced deep learning models,
                  trained on vast datasets, to deliver highly accurate
                  predictions for breast cancer detection. These models
                  continuously improve, ensuring the best possible outcomes and
                  assisting healthcare professionals in making data-driven
                  decisions for early diagnosis and treatment planning.
                </p>
              </div>
            </div>
          </div>

          <div className="pt-6">
            <div className="flow-root rounded-lg bg-gray-50 px-6 pb-8">
              <div className="-mt-6">
                <div>
                  <span className="inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 shadow-lg">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      className="h-6 w-6 text-white"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="M2.25 18 9 11.25l4.306 4.306a11.95 11.95 0 0 1 5.814-5.518l2.74-1.22m0 0-5.94-2.281m5.94 2.28-2.28 5.941"
                      />
                    </svg>
                  </span>
                </div>
                <h3 className="mt-8 text-lg font-medium tracking-tight text-gray-900">
                  Real-time results with actionable insights
                </h3>
                <p className="mt-5 text-base text-gray-500">
                  The app provides real-time analysis of medical images and
                  data, delivering immediate results that are easy to interpret.
                  These actionable insights enable healthcare professionals to
                  make timely and informed decisions, improving patient outcomes
                  and treatment effectiveness.
                </p>
              </div>
            </div>
          </div>
          <div className="pt-6">
            <div className="flow-root rounded-lg bg-gray-50 px-6 pb-8">
              <div className="-mt-6">
                <div>
                  <span className="inline-flex items-center justify-center rounded-md bg-indigo-500 p-3 shadow-lg">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke-width="1.5"
                      stroke="currentColor"
                      className="h-6 w-6 text-white"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        d="m3.75 13.5 10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75Z"
                      />
                    </svg>
                  </span>
                </div>
                <h3 className="mt-8 text-lg font-medium tracking-tight text-gray-900">
                  Fast and easy data upload.
                </h3>
                <p className="mt-5 text-base text-gray-500">
                  The app offers a seamless and intuitive process for uploading
                  medical images and patient data, allowing for quick
                  integration into the system. This user-friendly feature
                  ensures that healthcare providers can efficiently access and
                  analyze critical information without any delays.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
export default Features;
