import React from "react";
function Features() {
  return (
    <section className="bg-white py-24 sm:py-32">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl lg:text-center">
          <h2 className="text-base/7 font-semibold text-indigo-600">
            Key Features
          </h2>
        </div>
        <div className="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-4xl">
          <dl className="grid max-w-xl grid-cols-1 gap-x-8 gap-y-10 lg:max-w-none lg:grid-cols-2 lg:gap-y-16">
            <div className="relative pl-16">
              <dt className="text-base/7 font-semibold text-gray-900">
                Accurate predictions generated by powerful Deep Learning Models.{" "}
              </dt>
            </div>
            <div className="relative pl-16">
              <dt className="text-base/7 font-semibold text-gray-900">
                Fast and easy data upload.
              </dt>
            </div>
            <div className="relative pl-16">
              <dt className="text-base/7 font-semibold text-gray-900">
                Real-time results with actionable insights
              </dt>
            </div>
          </dl>
        </div>
      </div>
    </section>
  );
}
export default Features;
